{
 "title": "Vertica Test",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "select distinct NODE_NAME as '_text' from CPU_USAGE"
   }
  ]
 },
 "panels": [
  {
   "title": "Normal Time series example",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryString": "SELECT \n    time_slice(end_time, $__interval_ms, 'ms', 'end') as time , \n    node_name,\n    avg(average_cpu_usage_percent)\n  FROM \n   v_monitor.cpu_usage \n  WHERE \n   end_time > TO_TIMESTAMP($__from/1000) and end_time < TO_TIMESTAMP($__to/1000)\n   AND REGEXP_LIKE(NODE_NAME,'${node:regex}')\n  GROUP BY 1, 2\n  ORDER BY 1 asc",
     "streamingInterval": 1
    }
   ]
  },
  {
   "title": "streamng example",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryString": "select \nsysdate() as time,\nrandom() as kpia,\nrandom() as kpib,\nrandom() as kpic",
     "streamingInterval": 1
    }
   ]
  },
  {
   "title": "table example",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "queryString": "select * from DISK_STORAGE", "streamingInterval": 1 }
   ]
  }
 ]
}